apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: markenx-api-swagger
  namespace: markenx
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: markenx-api.local
      http:
        paths:
          - path: /(swagger-ui.*)
            pathType: Prefix
            backend:
              service:
                name: markenx-api
                port:
                  number: 80