apiVersion: apps/v1
kind: Deployment
metadata:
  name: markenx-api
  namespace: markenx
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: markenx-api
  template:
    metadata:
      labels:
        app: markenx-api
    spec:
      containers:
        - name: api
          image: markenx/markenx-api:v2.0.6-alpha
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: markenx-api-config
            - secretRef:
                name: markenx-db-secret
            - secretRef:
                name: keycloak-client-secret
          env:
            - name: KEYCLOAK_CREDENTIALS_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: client-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: 8080
            failureThreshold: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health/readiness
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: 8080
            periodSeconds: 20
