apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: markenx-api-ingress
  namespace: markenx
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ingressClassName: nginx
  rules:
    - host: markenx-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: markenx-api
                port:
                  number: 80