# This secret must match the client configuration in keycloak-realm-import.yaml
# The client-secret value must be identical in both places for authentication to work
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret
  namespace: markenx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  client-id: markenx-api
  client-secret: markenx-api-secret-change-me
  realm: markenx
  auth-server-url: http://keycloak-service:8080
  auth-server-url-external: http://keycloak.local
  issuer-uri: http://keycloak-service:8080/realms/markenx
  jwk-set-uri: http://keycloak-service:8080/realms/markenx/protocol/openid-connect/certs
