apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: markenx

resources:
  - keycloak-client-secret.yaml
  - api-configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-ingress.yaml
  - mysql
