apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrealmimports.k8s.keycloak.org
spec:
  group: k8s.keycloak.org
  names:
    kind: KeycloakRealmImport
    listKind: KeycloakRealmImportList
    plural: keycloakrealmimports
    singular: keycloakrealmimport
  scope: Namespaced
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
      subresources:
        status: {}