apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-infra
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MarkenX/markenx-config.git
    targetRevision: main
    path: k8s/base/keycloak

  destination:
    server: https://kubernetes.default.svc
    namespace: markenx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: k8s.keycloak.org
      kind: Keycloak
      managedFieldsManagers:
        - keycloak-operator
        - kubectl
        - kubectl-client-side-apply
        - argocd-controller
      jsonPointers:
        - /status
        - /spec/unsupported
