apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: markenx
data:
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_PROXY: "edge"
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_LOG_LEVEL: INFO
  KC_METRICS_ENABLED: "true"