apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: markenx
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_DATABASE_PASSWORD: changeme_secure_password
