apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: markenx
type: Opaque
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: changeme_secure_password