apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-namespace.yaml
  - nginx-ingress-class.yaml
  - nginx-cluster-role.yaml
  - nginx-cluster-role-binding.yaml
  - nginx-role.yaml
  - nginx-role-binding.yaml
  - nginx-service-account.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
