apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: markenx-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MarkenX/markenx-config.git
    targetRevision: main
    path: k8s/base

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: k8s.keycloak.org
      kind: Keycloak
      name: keycloak
      namespace: markenx
      jsonPointers:
        - /status
        - /metadata/generation
        - /metadata/resourceVersion
        - /metadata/annotations/kubectl.kubernetes.io~
