apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ArgoCD Applications must be deployed to the argocd namespace
namespace: argocd

resources:
  - api-application.yaml
  - keycloak-application.yaml
  - ngnix-application.yaml