apiVersion: v1
kind: Secret
metadata:
  name: markenx-db-secret
  namespace: markenx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: cm9vdA==
