apiVersion: apps/v1
kind: Deployment
metadata:
  name: markenx-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: markenx-api
  template:
    metadata:
      labels:
        app: markenx-api
    spec:
      containers:
        - name: api
          image: markenx/markenx-api:v2.0.6-alpha
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: markenx-api-config
            - secretRef:
                name: markenx-db-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
