apiVersion: apps/v1
kind: Deployment
metadata:
  name: markenx-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: markenx-api
  template:
    metadata:
      labels:
        app: markenx-api
    spec:
      containers:
        - name: api
          image: markenx/markenx-api:v2.0.3-alpha
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: markenx-api-config
            - secretRef:
                name: markenx-db-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 20
